import type { Config } from 'tailwindcss';

export default {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'text-recatch-text-hover',
    'hover:bg-recatch-text-hover',
    'active:bg-recatch-text-hover',
    'disabled:bg-recatch-text-hover',
    'duration-200',
    'border-radius-button',
    'padding-sx',
    'padding-sm',
    'text-base-normal',
    'text-recatch-text-secondary',
    'bg-recatch-text-light-solid',
    'border-[1px]',
    'border-recatch-border',
    'active:bg-recatch-text-tertiary',
    'disabled:text-recatch-text-disabled',
    'disabled:bg-recatch-disabled',
    'text-recatch-text-light-solid',
    'bg-recatch-primary',
    'border-recatch-primary',
    'hover:bg-recatch-primary-hover',
    'hover:border-recatch-primary-hover',
    'active:bg-recatch-primary-active',
    'active:border-recatch-primary-active',
    'disabled:border-recatch-border',
    'flex-shrink-0',
    'w-[16px]',
    'h-[16px]',
    'flex',
    'items-center',
    'justify-center',
    '!p-0',

    'w-full',
    'h-full',
    'absolute',
    'top-0',
    'left-0',
    'right-0',
    'bottom-0',
    'animate-fadeIn',
    'bg-black',
    'bg-opacity-50',
    'visible',
    'z-[500]',
    'z-[200]',
    'z-[-1]',
    'z-[-2]',

    'py-[5px]',
    'px-[12px]',
    'p-[8px]',
    'rounded-[10px]',
    'rounded-[6px]',
    'rounded-[8px]',
    'font-semibold',
    'text-[18px]',
    'leading-[24px]',
    'text-right',
    'font-normal',
    'text-[14px]',
    'leading-[22px]',
    'text-[16px]',
    'border-b-[1px]',
    'border-b-recatch-split',
    'bg-recatch-fill-alter',

    'text-left',
    'flex-shrink-0',
    'flex',
    'items-center',
    'justify-center',
    'flex-row',
    'w-[120px]',
    'flex-1',
    'w-0',
    'w-[200px]',
    'w-[150px]',
    'w-[48px]',
  ],
  theme: {
    extend: {
      fontFamily: {
        pretendard: ['Pretendard', 'Roboto'],
        roboto: ['Roboto', 'Roboto'],
      },
      colors: {
        recatch: {
          error: '#FF4D4F',
          primary: '#4A7CFE',
          'primary-hover': '#739FFF',
          'primary-active': '#345DD9',
          disabled: '#0000000A',
          border: '#E3E3E3',
          'text-hover': '#0000000F',
          'text-secondary': '#000000A6',
          'text-tertiary': '#00000073',
          'text-light-solid': '#FFFFFF',
          'text-disabled': '#00000040',
          'text-placeholder': '#00000040',
          'text-description': '#00000073',
          text: '#000000E0',
          'item-active': '#F0F7FF',
          'item-hover': '#0000000A',
          'fill-alter': '#00000005',
          split: '#0000000F',
          icon: '#00000073',
          'bg-active': '#F0F7FF',
        },
      },
      spacing: {
        vh: '1vh',
        vw: '1vw',
      },
      boxShadow: {
        'input-blur': '0px 0px 0px 2px rgba(74, 124, 254, 0.15)',
        'calendar-blur': `
          0px 9px 28px 8px rgba(0, 0, 0, 0.05),
          0px 3px 6px -4px rgba(0, 0, 0, 0.12),
          0px 6px 16px 0px rgba(0, 0, 0, 0.08)
        `,
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleUp: {
          '0%': { scale: '90%', opacity: '0' },
          '100%': { scale: '100%', opacity: '1' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.2s ease-in-out',
        scaleUp: 'scaleUp 0.2s ease-in-out',
      },
    },
  },
  plugins: [],
} satisfies Config;
